import { Router } from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import campaignRoutes from './campaign.routes.js';
import leadRoutes from './lead.routes.js';
import notificationRoutes from './notification.routes.js';
import webhookRoutes from './webhook.routes.js';
import feedbackRoutes from './feedback.routes.js';
import tagRoutes from './tag.routes.js';
import commentRoutes from './comment.routes.js';
import activityRoutes from './activity.routes.js';
import settingsRoutes from './settings.routes.js';
import reportRoutes from './report.routes.js';
import metaConnectionRoutes from './metaConnection.routes.js';
import departmentRoutes from './department.routes.js';
import designationRoutes from './designation.routes.js';
import mastersRoutes from './masters.routes.js';
import bookingRoutes from './booking.routes.js';
import packageRoutes from './packages.routes.js';
import erpRoutes from './erp.routes.js';
import itineraryRoutes from './itinerary.routes.js';
import paymentRoutes from './payment.routes.js';
import bookingTaskRoutes from './bookingTask.routes.js';
import operationsRoutes from './operations.routes.js';
import financeRoutes from './finance.routes.js';
import travelerPortalRoutes from './travelerPortal.routes.js';
import executiveRoutes from './executive.routes.js';
import analyticsRoutes from './analytics.routes.js';
import businessRuleRoutes from './businessRule.routes.js';
import automationRuleRoutes from './automationRule.routes.js';
import systemHealthRoutes from './systemHealth.routes.js';
import searchRoutes from './search.routes.js';
import hrRoutes from './hr.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/leads', leadRoutes);
router.use('/leads/:leadId/comments', commentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/tags', tagRoutes);
router.use('/activity', activityRoutes);
router.use('/settings', settingsRoutes);
router.use('/reports', reportRoutes);
router.use('/settings/meta-connection', metaConnectionRoutes);
router.use('/departments', departmentRoutes);
router.use('/designations', designationRoutes);
router.use('/masters', mastersRoutes);
router.use('/bookings', bookingRoutes);
router.use('/packages', packageRoutes);
router.use('/packages/:packageId/itinerary', itineraryRoutes);
router.use('/bookings/:bookingId/payments', paymentRoutes);
router.use('/payments', paymentRoutes);
router.use('/bookings/:bookingId/tasks', bookingTaskRoutes);
router.use('/tasks', bookingTaskRoutes);
router.use('/erp', erpRoutes);
router.use('/operations', operationsRoutes);
router.use('/finance', financeRoutes);
router.use('/portal', travelerPortalRoutes);
router.use('/executive', executiveRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/business-rules', businessRuleRoutes);
router.use('/automation-rules', automationRuleRoutes);
router.use('/system', systemHealthRoutes);
router.use('/search', searchRoutes);
router.use('/hr', hrRoutes);

export default router;
